import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx={console};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(new URL('../apps_script/Code.gs',import.meta.url),'utf8'),ctx);
const caseRow={id:'case-1',folder:'drive-case-1',status:'Collecting'};
const docs=[],actions=[];let saved;
ctx.requireManager_=()=>({email:'reviewer@example.test'});
ctx.lock_=fn=>fn();
ctx.rows_=name=>name==='01_SO_MASTER'?[caseRow]:name==='06_DOCUMENT_REGISTER'?docs:[];
ctx.Utilities={base64Decode:data=>[...Buffer.from(data,'base64')],newBlob:(bytes,type,name)=>({bytes,type,name})};
ctx.DriveApp={getFolderById:id=>{assert.equal(id,caseRow.folder);return {getFoldersByName:name=>{assert.equal(name,'99_FINAL');return {hasNext:()=>true,next:()=>({createFile:blob=>{saved=blob;return {getId:()=> 'drive-file-1'};}})}}};}};
ctx.add_=(sheet,row)=>{assert.equal(sheet,'06_DOCUMENT_REGISTER');docs.push(row);};
ctx.audit_=(...a)=>actions.push(a);
ctx.uid_=()=> 'document-1';ctx.now_=()=> '2026-10-06T00:00:00Z';
const pdf=Buffer.from('%PDF-1.7\n').toString('base64');
assert.throws(()=>ctx.uploadOutput('case-1',{name:'bad.pdf',type:'application/pdf',data:Buffer.from('plain').toString('base64')}),/PDF must be valid/);
assert.throws(()=>ctx.uploadOutput('wrong',{name:'good.pdf',type:'application/pdf',data:pdf}),/Case not found/);
const result=ctx.uploadOutput('case-1',{name:'output.pdf',type:'application/pdf',data:pdf});
assert.equal(result.version,1);assert.equal(docs[0].file_id,'drive-file-1');assert.equal(docs[0].status,'Draft');assert.equal(saved.name,'output.pdf');assert.equal(actions[0][0],'OUTPUT_UPLOADED');
console.log('Direct output upload authorization, PDF validation, and document register passed (mocked Drive).');
